### ISSUE TITLE
Socketerror while testing SSH targets

### ISSUE THREAD

**Issue by michaelkrieg** [dev-sec/ssl-baseline#21]
Hi,

if I try running this profile I get the following error:

`
inspec  exec https://github.com/dev-sec/ssl-baseline -t ssh://user@host:port
[2018-06-20T07:59:14+02:00] WARN: URL target https://github.com/dev-sec/ssl-baseline transformed to https://github.com/dev-sec/ssl-baseline/archive/master.tar.gz. Consider using the git fetcher
/Users/michael/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/sslshake-1.2.0/lib/sslshake.rb:20:in `getaddrinfo': getaddrinfo: nodename nor servname provided, or not known (SocketError)
	from /Users/michael/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/sslshake-1.2.0/lib/sslshake.rb:20:in `socket'
	from /Users/michael/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/sslshake-1.2.0/lib/sslshake.rb:54:in `hello'
	from /Users/michael/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/inspec-2.2.16/lib/resources/ssl.rb:72:in `block (2 levels) in <class:SSL>'
	from /Users/michael/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/parallel-1.12.1/lib/parallel.rb:484:in `call_with_index'
	from /Users/michael/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/parallel-1.12.1/lib/parallel.rb:342:in `block (2 levels) in work_in_threads'
	from /Users/michael/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/parallel-1.12.1/lib/parallel.rb:495:in `with_instrumentation'
	from /Users/michael/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/parallel-1.12.1/lib/parallel.rb:341:in `block in work_in_threads'
	from /Users/michael/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/parallel-1.12.1/lib/parallel.rb:206:in `block (2 levels) in in_threads'
`

The same test-target works fine with any other dev-sec tests (e.g.: linux-baseline oder linux-patch-baseline). 

I also tested against different target hosts - same result.

I have never seen this before, since this always works well in the past. 

Can you please advise, because the error message seems clear on the one hand and totally strange on the other hand.

Thanks!

Best,
  Micha

**Comment by artem-sidorenko** [comment]
@michaelkrieg thanks for this bug report!

@chris-rock @atomic111 any ideas?
